server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinic_db?useSSL=false&serverTimezone=UTC
    username: your_db_username
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      # Use 'update' for dev, 'validate' or 'none' for production
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: VerySecretKeyForJwtGenerationChangeThis1234567890
  expiration: 86400000  # 1 day in milliseconds

logging:
  level:
    org.springframework: INFO
    com.bms.clinicmanagementsystem: DEBUG

# Optional: Configure file upload size limits if you handle files
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
